spring:
  application:
    name: lms-demo
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'
    username: local
    password: 1234
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-view: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
jwt:
  secret: E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855
  expires-in-mills: 86400000 # 1 day
lock-client:
  redisson:
    address: "redis://127.0.0.1:6379"
    database: 0
